# Unlikely to be necessary after upgrading to bullseye (needed to pull in python3-firewall)
- name: Add backports repo
  apt_repository:
    repo: deb http://deb.debian.org/debian {{ ansible_distribution_release }}-backports main
    state: present
    filename: backports
  notify:
    - update apt

- name: Install firewalld & python bindings
  apt:
    name:
      - firewalld  # Required for ansible.posix.firewalld
      - python3-firewall
      - iptables   # Newer version fixes a bug in buster iptables
      - sshguard   # Helpful at blocking ssh attacks
    default_release: "{{ ansible_distribution_release }}-backports"
    state: present

- name: Configure firewalld
  lineinfile:
    path: /etc/firewalld/firewalld.conf
    regexp: "^FirewallBackend="
    line: "FirewallBackend=nftables"
  notify:
    - restart firewalld

- name: Configure firewall rules
  ansible.posix.firewalld:
    permanent: true
    state: enabled
    port: "{{ item }}"
  with_items: "{{ firewall_open_ports }}"
  notify:
    - restart firewalld

- name: Create sshguard blacklist db directory
  file:
    path: /var/db/sshguard
    state: directory

- name: Configure sshguard
  lineinfile:
    path: /etc/sshguard/sshguard.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    # Use firewalld backend
    - regexp: "^BACKEND="
      line: 'BACKEND="/usr/lib/x86_64-linux-gnu/sshg-fw-firewalld"'
    # Workaround https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=928525
    - regexp: "^LOGREADER="
      line: 'LOGREADER="LANG=C /bin/journalctl -afb -p info -t sshd -n1 -o cat"'
    # Set persistent blacklist
    - regexp: "^BLACKLIST_FILE="
      line: 'BLACKLIST_FILE=100:/var/db/sshguard/blacklist.db'
  notify:
    - restart sshguard
