- name: restart sshguard
  service:
    name: sshguard
    state: restarted

- name: restart firewalld
  service:
    name: firewalld
    state: restarted

- name: update apt
  apt:
    update_cache: true
