- hosts: bananas_fileservers
  gather_facts: true
  become: true

  roles:
    - ovh  # Do this as early as possible to ensure ipv6 is configured and working
    - standard-setup
    - geerlingguy.certbot
    - geerlingguy.nginx

  tasks:
    - name: Force nginx handlers to run before testing nginx
      meta: flush_handlers

    - name: Test HTTPS to health check endpoint
      uri:
        url: https://{{ inventory_hostname }}/healthz
        status_code: 200
      delegate_to: localhost
      become: false

    # Note that, in effect, this tests against 'localhost', but also tests connecting to upstream
    # Doesn't quite test actual external access, but it's much faster than waiting for my slow internet connection
    - name: Test download of particular item (OGFX)
      uri:
        url: "{{ item }}://{{ inventory_hostname }}/base-graphics/4f474658/99ef7df70a3fe95f0f9da6dcb5e63444/FOR-TESTING-ONLY.tar.gz"
        status_code: 200
      with_items:
        - http
        - https
      become: false
